### ISSUE TITLE
Can't get it to compile on Ubuntu 20.10

### ISSUE THREAD

**Issue by JonMaliepaard** [andrepatta/etn-desktop-wallet#10]
Hi, wish there was a way that I could access an old wallet (from mining days) only have  a password and a seed. No private keys.
Compile fails
QT5.14.2-2

Error:

../src/libwalletqt/WalletManager.cpp:50:16: error: ‘virtual void WalletPassphraseListenerImpl::moneySpent(const string&, uint64_t)’ marked ‘override’, but does not override
   50 |   virtual void moneySpent(const std::string &txId, uint64_t amount) override { (void)txId; (void)amount; };
      |                ^~~~~~~~~~
../src/libwalletqt/WalletManager.cpp:51:16: error: ‘virtual void WalletPassphraseListenerImpl::moneyReceived(const string&, uint64_t)’ marked ‘override’, but does not override
   51 |   virtual void moneyReceived(const std::string &txId, uint64_t amount) override { (void)txId; (void)amount; };
      |                ^~~~~~~~~~~~~
../src/libwalletqt/WalletManager.cpp:52:16: error: ‘virtual void WalletPassphraseListenerImpl::unconfirmedMoneyReceived(const string&, uint64_t)’ marked ‘override’, but does not override
   52 |   virtual void unconfirmedMoneyReceived(const std::string &txId, uint64_t amount) override { (void)txId; (void)amount; };
      |                ^~~~~~~~~~~~~~~~~~~~~~~~
../src/libwalletqt/WalletManager.cpp: In member function ‘Wallet* WalletManager::openWallet(const QString&, const QString&, NetworkType::Type, quint64)’:
../src/libwalletqt/WalletManager.cpp:124:34: error: cannot declare variable ‘tmpListener’ to be of abstract type ‘WalletPassphraseListenerImpl’
  124 |     WalletPassphraseListenerImpl tmpListener(this);
      |                                  ^~~~~~~~~~~
../src/libwalletqt/WalletManager.cpp:45:7: note:   because the following virtual functions are pure within ‘WalletPassphraseListenerImpl’:
   45 | class WalletPassphraseListenerImpl : public  Electroneum::WalletListener
      |       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from ../src/libwalletqt/WalletManager.h:36,
                 from ../src/libwalletqt/WalletManager.cpp:30:
../electroneum/include/wallet/api/wallet2_api.h:350:18: note:     ‘virtual void Electroneum::WalletListener::etnSpent(const string&, uint64_t)’
  350 |     virtual void etnSpent(const std::string &txId, uint64_t amount) = 0;
      |                  ^~~~~~~~
../electroneum/include/wallet/api/wallet2_api.h:357:18: note:     ‘virtual void Electroneum::WalletListener::etnReceived(const string&, uint64_t)’
  357 |     virtual void etnReceived(const std::string &txId, uint64_t amount) = 0;
      |                  ^~~~~~~~~~~
../electroneum/include/wallet/api/wallet2_api.h:364:18: note:     ‘virtual void Electroneum::WalletListener::unconfirmedETNReceived(const string&, uint64_t)’
  364 |     virtual void unconfirmedETNReceived(const std::string &txId, uint64_t amount) = 0;
      |                  ^~~~~~~~~~~~~~~~~~~~~~
../src/libwalletqt/WalletManager.cpp: In member function ‘Wallet* WalletManager::createWalletFromDevice(const QString&, const QString&, NetworkType::Type, const QString&, quint64, const QString&)’:
../src/libwalletqt/WalletManager.cpp:187:34: error: cannot declare variable ‘tmpListener’ to be of abstract type ‘WalletPassphraseListenerImpl’
  187 |     WalletPassphraseListenerImpl tmpListener(this);
      |                                  ^~~~~~~~~~~
make: *** [Makefile:1815: WalletManager.o] Error 1

**Comment by JonMaliepaard** [comment]
Installed QT5.9.9, as suggested, directly from Qt. Set environmental variables to use that compiler. Have the same problems? Any idea? Thanks
Problems start here 
--snip--
g++ -c -pipe -fPIC -fstack-protector -fstack-protector-strong -fPIC -fstack-protector -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -Wformat -Wformat-security -O2 -std=gnu++11 -Wall -W -D_REENTRANT -fPIC -DQT_NO_DEBUG -DQT_SVG_LIB -DQT_WIDGETS_LIB -DQT_QUICK_LIB -DQT_GUI_LIB -DQT_QML_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -I../../etn-desktop-wallet -I. -I../electroneum/include -I../src/libwalletqt -I../src/QR-Code-generator -I../src -I../electroneum/src -isystem /usr/include/hidapi -I../../Qt/5.9.9/gcc_64/include -I../../Qt/5.9.9/gcc_64/include/QtSvg -I../../Qt/5.9.9/gcc_64/include/QtWidgets -I../../Qt/5.9.9/gcc_64/include/QtGui/5.9.9 -I../../Qt/5.9.9/gcc_64/include/QtGui/5.9.9/QtGui -I../../Qt/5.9.9/gcc_64/include/QtQuick -I../../Qt/5.9.9/gcc_64/include/QtGui -I../../Qt/5.9.9/gcc_64/include/QtQml -I../../Qt/5.9.9/gcc_64/include/QtNetwork -I../../Qt/5.9.9/gcc_64/include/QtCore/5.9.9 -I../../Qt/5.9.9/gcc_64/include/QtCore/5.9.9/QtCore -I../../Qt/5.9.9/gcc_64/include/QtCore -I. -isystem /usr/include/libdrm -I../../Qt/5.9.9/gcc_64/mkspecs/linux-g++ -o main.o ../main.cpp
In file included from ../../Qt/5.9.9/gcc_64/include/QtCore/qlocale.h:43,
                 from ../../Qt/5.9.9/gcc_64/include/QtGui/qguiapplication.h:47,
                 from ../../Qt/5.9.9/gcc_64/include/QtWidgets/qapplication.h:52,
                 from ../../Qt/5.9.9/gcc_64/include/QtWidgets/QApplication:1,
                 from ../main.cpp:30:
../../Qt/5.9.9/gcc_64/include/QtCore/qvariant.h: In constructor ‘QVariant::QVariant(QVariant&&)’:
../../Qt/5.9.9/gcc_64/include/QtCore/qvariant.h:265:25: warning: implicitly-declared ‘QVariant::Private& QVariant::Private::operator=(const QVariant::Private&)’ is deprecated [-Wdeprecated-copy]
  265 |     { other.d = Private(); }
      |                         ^
../../Qt/5.9.9/gcc_64/include/QtCore/qvariant.h:380:16: note: because ‘QVariant::Private’ has user-provided ‘QVariant::Private::Private(const QVariant::Private&)’
  380 |         inline Private(const Private &other) Q_DECL_NOTHROW
      |                ^~~~~~~
g++ -c -pipe -fPIC -fstack-protector -fstack-protector-strong -fPIC -fstack-protector -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -Wformat -Wformat-security -O2 -std=gnu++11 -Wall -W -D_REENTRANT -fPIC -DQT_NO_DEBUG -DQT_SVG_LIB -DQT_WIDGETS_LIB -DQT_QUICK_LIB -DQT_GUI_LIB -DQT_QML_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -I../../etn-desktop-wallet -I. -I../electroneum/include -I../src/libwalletqt -I../src/QR-Code-generator -I../src -I../electroneum/src -isystem /usr/include/hidapi -I../../Qt/5.9.9/gcc_64/include -I../../Qt/5.9.9/gcc_64/include/QtSvg -I../../Qt/5.9.9/gcc_64/include/QtWidgets -I../../Qt/5.9.9/gcc_64/include/QtGui/5.9.9 -I../../Qt/5.9.9/gcc_64/include/QtGui/5.9.9/QtGui -I../../Qt/5.9.9/gcc_64/include/QtQuick -I../../Qt/5.9.9/gcc_64/include/QtGui -I../../Qt/5.9.9/gcc_64/include/QtQml -I../../Qt/5.9.9/gcc_64/include/QtNetwork -I../../Qt/5.9.9/gcc_64/include/QtCore/5.9.9 -I../../Qt/5.9.9/gcc_64/include/QtCore/5.9.9/QtCore -I../../Qt/5.9.9/gcc_64/include/QtCore -I. -isystem /usr/include/libdrm -I../../Qt/5.9.9/gcc_64/mkspecs/linux-g++ -o WalletManager.o ../src/libwalletqt/WalletManager.cpp
In file included from ../../Qt/5.9.9/gcc_64/include/QtCore/QVariant:1,
                 from ../src/libwalletqt/WalletManager.h:33,
                 from ../src/libwalletqt/WalletManager.cpp:30:
../../Qt/5.9.9/gcc_64/include/QtCore/qvariant.h: In constructor ‘QVariant::QVariant(QVariant&&)’:
../../Qt/5.9.9/gcc_64/include/QtCore/qvariant.h:265:25: warning: implicitly-declared ‘QVariant::Private& QVariant::Private::operator=(const QVariant::Private&)’ is deprecated [-Wdeprecated-copy]
  265 |     { other.d = Private(); }
      |                         ^
../../Qt/5.9.9/gcc_64/include/QtCore/qvariant.h:380:16: note: because ‘QVariant::Private’ has user-provided ‘QVariant::Private::Private(const QVariant::Private&)’
  380 |         inline Private(const Private &other) Q_DECL_NOTHROW
      |                ^~~~~~~
../src/libwalletqt/WalletManager.cpp: At global scope:
../src/libwalletqt/WalletManager.cpp:50:16: error: ‘virtual void WalletPassphraseListenerImpl::moneySpent(const string&, uint64_t)’ marked ‘override’, but does not override
   50 |   virtual void moneySpent(const std::string &txId, uint64_t amount) override { (void)txId; (void)amount; };
      |                ^~~~~~~~~~
../src/libwalletqt/WalletManager.cpp:51:16: error: ‘virtual void WalletPassphraseListenerImpl::moneyReceived(const string&, uint64_t)’ marked ‘override’, but does not override
   51 |   virtual void moneyReceived(const std::string &txId, uint64_t amount) override { (void)txId; (void)amount; };
      |                ^~~~~~~~~~~~~
../src/libwalletqt/WalletManager.cpp:52:16: error: ‘virtual void WalletPassphraseListenerImpl::unconfirmedMoneyReceived(const string&, uint64_t)’ marked ‘override’, but does not override
   52 |   virtual void unconfirmedMoneyReceived(const std::string &txId, uint64_t amount) override { (void)txId; (void)amount; };
      |                ^~~~~~~~~~~~~~~~~~~~~~~~
../src/libwalletqt/WalletManager.cpp: In member function ‘Wallet* WalletManager::openWallet(const QString&, const QString&, NetworkType::Type, quint64)’:
../src/libwalletqt/WalletManager.cpp:124:34: error: cannot declare variable ‘tmpListener’ to be of abstract type ‘WalletPassphraseListenerImpl’
  124 |     WalletPassphraseListenerImpl tmpListener(this);
      |                                  ^~~~~~~~~~~
../src/libwalletqt/WalletManager.cpp:45:7: note:   because the following virtual functions are pure within ‘WalletPassphraseListenerImpl’:
   45 | class WalletPassphraseListenerImpl : public  Electroneum::WalletListener
      |       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from ../src/libwalletqt/WalletManager.h:36,
                 from ../src/libwalletqt/WalletManager.cpp:30:
../electroneum/include/wallet/api/wallet2_api.h:350:18: note:     ‘virtual void Electroneum::WalletListener::etnSpent(const string&, uint64_t)’
  350 |     virtual void etnSpent(const std::string &txId, uint64_t amount) = 0;
      |                  ^~~~~~~~
../electroneum/include/wallet/api/wallet2_api.h:357:18: note:     ‘virtual void Electroneum::WalletListener::etnReceived(const string&, uint64_t)’
  357 |     virtual void etnReceived(const std::string &txId, uint64_t amount) = 0;
      |                  ^~~~~~~~~~~
../electroneum/include/wallet/api/wallet2_api.h:364:18: note:     ‘virtual void Electroneum::WalletListener::unconfirmedETNReceived(const string&, uint64_t)’
  364 |     virtual void unconfirmedETNReceived(const std::string &txId, uint64_t amount) = 0;
      |                  ^~~~~~~~~~~~~~~~~~~~~~
../src/libwalletqt/WalletManager.cpp: In member function ‘Wallet* WalletManager::createWalletFromDevice(const QString&, const QString&, NetworkType::Type, const QString&, quint64, const QString&)’:
../src/libwalletqt/WalletManager.cpp:187:34: error: cannot declare variable ‘tmpListener’ to be of abstract type ‘WalletPassphraseListenerImpl’
  187 |     WalletPassphraseListenerImpl tmpListener(this);
      |                                  ^~~~~~~~~~~
make: *** [Makefile:4990: WalletManager.o] Error 1
